Repository OpenBazaar/multiwallet, pull requests merged in 2019-12, with the labels that each got.

#103 Do not mark wallet address as watched
  service/wallet_service.go
Labels: ordering, 🔍 readyForReview

#109 Update zcash branchID
  zcash/sign.go
  zcash/sign_test.go
Labels: 🔍 readyForReview

#111 Check and correct WatchOnly txn issues
  service/wallet_service.go
Labels: 🔍 readyForReview

#104 (#1899) Revert to original transports for API requests
  bitcoincash/exchange_rates.go
  client/blockbook/client.go
  litecoin/exchange_rates.go
  zcash/exchange_rates.go
Labels: enhancement, multiwallet, ordering, 🔍 readyForReview

#108 (#1919 ob-go) Migrate to AddWatchedAddresses
  Gopkg.lock
  bitcoin/wallet.go
  bitcoincash/wallet.go
  client/blockbook/client.go
  client/pool.go
  datastore/mock.go
  litecoin/wallet.go
  model/interfaces.go
  model/mock/interfaces.go
  service/wallet_service.go
  zcash/wallet.go
Labels: multiwallet, ordering, 🔍 readyForReview
