Repository OpenBazaar/multiwallet, pull requests merged in 2020-01, with the labels that each got.

#100 Limit Max inflight queries to blockbook.
  client/blockbook/client.go
  litecoin/address/address.go
Labels: ordering, 🚧 in progress

#120 Ensure addresses are sent as a slice
  client/blockbook/client.go
Labels: bug

#101 Update codebase with needed ethereum changes
  Gopkg.lock
  Gopkg.toml
  api/rpc.go
  bitcoin/sign.go
  bitcoin/sign_test.go
  bitcoin/wallet.go
  bitcoincash/exchange_rates.go
  bitcoincash/sign.go
  bitcoincash/sign_test.go
  bitcoincash/wallet.go
  config/config.go
  datastore/mock.go
  litecoin/exchange_rates.go
  litecoin/sign.go
  litecoin/sign_test.go
  litecoin/wallet.go
  multiwallet.go
  service/wallet_service.go
  service/wallet_service_test.go
  util/balance.go
  util/balance_test.go
  util/coin.go
  util/coin_test.go
  util/fees_test.go
  zcash/address/address.go
  zcash/exchange_rates.go
  zcash/sign.go
  zcash/sign_test.go
  zcash/wallet.go
  zcash/wallet_test.go
Labels: ethereum, 🚧 in progress
